const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '../.env.local' });

const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const rawData = `
EF09HI01 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. Experiências republicanas e práticas autoritárias: as tensões e disputas do mundo contemporâneo. A proclamação da República e seus primeiros desdobramentos | Descrever e contextualizar os principais aspectos sociais, culturais, econômicos e políticos da emergência da República no Brasil.
EF09HI02 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. Experiências republicanas e práticas autoritárias: as tensões e disputas do mundo contemporâneo. A proclamação da República e seus primeiros desdobramentos | Caracterizar e compreender os ciclos da história republicana, identificando particularidades da história local e regional até 1954.
EF09HI03 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. A questão da inserção dos negros no período republicano do pós-abolição. Os movimentos sociais e a imprensa negra: a cultura afro-brasileira como elemento de resistência e superação das discriminações | Identificar os mecanismos de inserção dos negros na sociedade brasileira pós-abolição e avaliar os seus resultados.
EF09HI04 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. A questão da inserção dos negros no período republicano do pós-abolição. Os movimentos sociais e a imprensa negra: a cultura afro-brasileira como elemento de resistência e superação das discriminações | Discutir a importância da participação da população negra na formação econômica, política e social do Brasil.
EF09HI05 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. Primeira República e suas características. Contestações e dinâmicas da vida cultural no Brasil entre 1900 e 1930 | Identificar os processos de urbanização e modernização da sociedade brasileira e avaliar suas contradições e impactos na região em que vive.
EF09HI06 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. O período varguista e suas contradições. A emergência da vida urbana e a segregação espacial. O trabalhismo e seu protagonismo político | Identificar e discutir o papel do trabalhismo como força política, social e cultural no Brasil, em diferentes escalas (nacional, regional, cidade, comunidade).
EF09HI07 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. A questão indígena durante a República (até 1964). Anarquismo e protagonismo feminino | Identificar e explicar, em meio a lógicas de inclusão e exclusão, as pautas dos povos indígenas, no contexto republicano (até 1964), e das populações afrodescendentes.
EF09HI08 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. A questão indígena durante a República (até 1964). Anarquismo e protagonismo feminino | Identificar as transformações ocorridas no debate sobre as questões da diversidade no Brasil durante o século XX e compreender o significado das mudanças de abordagem em relação ao tema.
EF09HI09 | O nascimento da República no Brasil e os processos históricos até a metade do século XX. A questão indígena durante a República (até 1964). Anarquismo e protagonismo feminino | Relacionar as conquistas de direitos políticos, sociais e civis à atuação de movimentos sociais.
EF09HI10 | Totalitarismos e conflitos mundiais. O mundo em conflito: a Primeira Guerra Mundial. A questão da Palestina. A Revolução Russa. A crise capitalista de 1929 | Identificar e relacionar as dinâmicas do capitalismo e suas crises, os grandes conflitos mundiais e os conflitos vivenciados na Europa.
EF09HI11 | Totalitarismos e conflitos mundiais. O mundo em conflito: a Primeira Guerra Mundial. A questão da Palestina. A Revolução Russa. A crise capitalista de 1929 | Identificar as especificidades e os desdobramentos mundiais da Revolução Russa e seu significado histórico.
EF09HI12 | Totalitarismos e conflitos mundiais. O mundo em conflito: a Primeira Guerra Mundial. A questão da Palestina. A Revolução Russa. A crise capitalista de 1929 | Analisar a crise capitalista de 1929 e seus desdobramentos em relação à economia global.
EF09HI13 | Totalitarismos e conflitos mundiais. A emergência do fascismo e do nazismo. A Segunda Guerra Mundial. Judeus e outras vítimas do holocausto | Descrever e contextualizar os processos da emergência do fascismo e do nazismo, a consolidação dos estados totalitários e as práticas de extermínio (como o holocausto).
EF09HI14 | Totalitarismos e conflitos mundiais. O colonialismo na África. As guerras mundiais, a crise do colonialismo e o advento dos nacionalismos africanos e asiáticos | Caracterizar e discutir as dinâmicas do colonialismo no continente africano e asiático e as lógicas de resistência das populações locais diante das questões internacionais.
EF09HI15 | Totalitarismos e conflitos mundiais. A Organização das Nações Unidas (ONU) e a questão dos Direitos Humanos | Discutir as motivações que levaram à criação da Organização das Nações Unidas (ONU) no contexto do pós-guerra e os propósitos dessa organização.
EF09HI16 | Totalitarismos e conflitos mundiais. A Organização das Nações Unidas (ONU) e a questão dos Direitos Humanos | Relacionar a Carta dos Direitos Humanos ao processo de afirmação dos direitos fundamentais e de defesa da dignidade humana, valorizando as instituições voltadas para a defesa desses direitos e para a solidariedade internacional.
EF09HI17 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O Brasil da era JK e o ideal de uma nação moderna: a urbanização e seus desdobramentos em um país em transformação | Identificar e analisar processos sociais, econômicos, culturais e políticos do Brasil a partir de 1946.
EF09HI18 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O Brasil da era JK e o ideal de uma nação moderna: a urbanização e seus desdobramentos em um país em transformação | Descrever e analisar as relações entre as transformações urbanas e seus impactos na cultura brasileira entre 1946 e 1964 e na produção das desigualdades regionais e sociais.
EF09HI19 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. Os anos 1960: revolução cultural? A ditadura civil-militar e os processos de resistência. As questões indígena e negra e a ditadura | Identificar e compreender o processo que resultou na ditadura civil-militar no Brasil e discutir a emergência de questões relacionadas à memória e à justiça sobre os casos de violação dos direitos humanos.
EF09HI20 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. Os anos 1960: revolução cultural? A ditadura civil-militar e os processos de resistência. As questões indígena e negra e a ditadura | Discutir os processos de resistência e as propostas de reorganização da sociedade brasileira durante a ditadura civil-militar.
EF09HI21 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. Os anos 1960: revolução cultural? A ditadura civil-militar e os processos de resistência. As questões indígena e negra e a ditadura | Identificar e relacionar as demandas indígenas e quilombolas como forma de contestação ao modelo desenvolvimentista da ditadura.
EF09HI22 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O processo de redemocratização. A Constituição de 1988 e a emancipação das cidadanias (analfabetos, indígenas, negros, jovens etc.). A história recente do Brasil: transformações políticas, econômicas, sociais e culturais de 1989 aos dias atuais. Os protagonismos da sociedade civil e as alterações da sociedade brasileira. A questão da violência contra populações marginalizadas. O Brasil e suas relações internacionais na era da globalização | Discutir o papel da mobilização da sociedade brasileira do final do período ditatorial até a Constituição de 1988.
EF09HI23 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O processo de redemocratização. A Constituição de 1988 e a emancipação das cidadanias (analfabetos, indígenas, negros, jovens etc.). A história recente do Brasil: transformações políticas, econômicas, sociais e culturais de 1989 aos dias atuais. Os protagonismos da sociedade civil e as alterações da sociedade brasileira. A questão da violência contra populações marginalizadas. O Brasil e suas relações internacionais na era da globalização | Identificar direitos civis, políticos e sociais expressos na Constituição de 1988 e relacioná-los à noção de cidadania e ao pacto da sociedade brasileira de combate a diversas formas de preconceito, como o racismo.
EF09HI24 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O processo de redemocratização. A Constituição de 1988 e a emancipação das cidadanias (analfabetos, indígenas, negros, jovens etc.). A história recente do Brasil: transformações políticas, econômicas, sociais e culturais de 1989 aos dias atuais. Os protagonismos da sociedade civil e as alterações da sociedade brasileira. A questão da violência contra populações marginalizadas. O Brasil e suas relações internacionais na era da globalização | Analisar as transformações políticas, econômicas, sociais e culturais de 1989 aos dias atuais, identificando questões prioritárias para a promoção da cidadania e dos valores democráticos.
EF09HI25 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O processo de redemocratização. A Constituição de 1988 e a emancipação das cidadanias (analfabetos, indígenas, negros, jovens etc.). A história recente do Brasil: transformações políticas, econômicas, sociais e culturais de 1989 aos dias atuais. Os protagonismos da sociedade civil e as alterações da sociedade brasileira. A questão da violência contra populações marginalizadas. O Brasil e suas relações internacionais na era da globalização | Relacionar as transformações da sociedade brasileira aos protagonismos da sociedade civil após 1989.
EF09HI26 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O processo de redemocratização. A Constituição de 1988 e a emancipação das cidadanias (analfabetos, indígenas, negros, jovens etc.). A história recente do Brasil: transformações políticas, econômicas, sociais e culturais de 1989 aos dias atuais. Os protagonismos da sociedade civil e as alterações da sociedade brasileira. A questão da violência contra populações marginalizadas. O Brasil e suas relações internacionais na era da globalização | Discutir e analisar as causas da violência contra populações marginalizadas (negros, indígenas, mulheres, homossexuais, camponeses, pobres etc.) com vistas à tomada de consciência e à construção de uma cultura de paz, empatia e respeito às pessoas.
EF09HI27 | Modernização, ditadura civil-militar e redemocratização: o Brasil após 1946. O processo de redemocratização. A Constituição de 1988 e a emancipação das cidadanias (analfabetos, indígenas, negros, jovens etc.). A história recente do Brasil: transformações políticas, econômicas, sociais e culturais de 1989 aos dias atuais. Os protagonismos da sociedade civil e as alterações da sociedade brasileira. A questão da violência contra populações marginalizadas. O Brasil e suas relações internacionais na era da globalização | Relacionar aspectos das mudanças econômicas, culturais e sociais ocorridas no Brasil a partir da década de 1990 ao papel do País no cenário internacional na era da globalização.
EF09HI28 | A história recente. A Guerra Fria: confrontos de dois modelos políticos. A Revolução Chinesa e as tensões entre China e Rússia. A Revolução Cubana e as tensões entre Estados Unidos da América e Cuba. As experiências ditatoriais na América Latina | Identificar e analisar aspectos da Guerra Fria, seus principais conflitos e as tensões geopolíticas no interior dos blocos liderados por soviéticos e estadunidenses.
EF09HI29 | A história recente. A Guerra Fria: confrontos de dois modelos políticos. A Revolução Chinesa e as tensões entre China e Rússia. A Revolução Cubana e as tensões entre Estados Unidos da América e Cuba. As experiências ditatoriais na América Latina | Descrever e analisar as experiências ditatoriais na América Latina, seus procedimentos e vínculos com o poder, em nível nacional e internacional, e a atuação de movimentos de contestação às ditaduras.
EF09HI30 | A história recente. A Guerra Fria: confrontos de dois modelos políticos. A Revolução Chinesa e as tensões entre China e Rússia. A Revolução Cubana e as tensões entre Estados Unidos da América e Cuba. As experiências ditatoriais na América Latina | Comparar as características dos regimes ditatoriais latino-americanos, com especial atenção para a censura política, a opressão e o uso da força, bem como para as reformas econômicas e sociais e seus impactos.
EF09HI31 | A história recente. Os processos de descolonização na África e na Ásia | Descrever e avaliar os processos de descolonização na África e na Ásia.
EF09HI32 | A história recente. O fim da Guerra Fria e o processo de globalização. Políticas econômicas na América Latina | Analisar mudanças e permanências associadas ao processo de globalização, considerando os argumentos dos movimentos críticos às políticas globais.
EF09HI33 | A história recente. O fim da Guerra Fria e o processo de globalização. Políticas econômicas na América Latina | Analisar as transformações nas relações políticas locais e globais geradas pelo desenvolvimento das tecnologias digitais de informação e comunicação.
EF09HI34 | A história recente. O fim da Guerra Fria e o processo de globalização. Políticas econômicas na América Latina | Discutir as motivações da adoção de diferentes políticas econômicas na América Latina, assim como seus impactos sociais nos países da região.
EF09HI35 | A história recente. Os conflitos do século XXI e a questão do terrorismo. Pluralidades e diversidades identitárias na atualidade. As pautas dos povos indígenas no século XXI e suas formas de inserção no debate local, regional, nacional e internacional | Analisar os aspectos relacionados ao fenômeno do terrorismo na contemporaneidade, incluindo os movimentos migratórios e os choques entre diferentes grupos e culturas.
EF09HI36 | A história recente. Os conflitos do século XXI e a questão do terrorismo. Pluralidades e diversidades identitárias na atualidade. As pautas dos povos indígenas no século XXI e suas formas de inserção no debate local, regional, nacional e internacional | Identificar e discutir as diversidades identitárias e seus significados históricos no início do século XXI, combatendo qualquer forma de preconceito e violência.
`;

async function importSkills() {
    const lines = rawData.trim().split('\n');
    const skillsToInsert = [];
    for (let line of lines) {
        if (!line.trim()) continue;
        const parts = line.split('|').map(p => p.trim());
        if (parts.length >= 3) {
            const code = parts[0];
            const knowledgeObject = parts[1];
            const description = parts.slice(2).join(' | ');
            const yearMatch = code.match(/EF(\d{2})/);
            const year_range = yearMatch ? "EF" + yearMatch[1] : "EF00";
            const fullDescription = "[Objeto de Conhecimento: " + knowledgeObject + "] " + description;

            skillsToInsert.push({ code, description: fullDescription, subject: "HISTÓRIA", year_range });
        }
    }
    if (skillsToInsert.length === 0) { console.log("Nenhuma habilidade encontrada."); return; }
    console.log("Preparando para inserir " + skillsToInsert.length + " habilidades...");
    const { data: result, error } = await supabase.from('bncc_skills').upsert(skillsToInsert, { onConflict: 'code' }).select();
    if (error) { console.error("Erro na inserção:", error); }
    else { console.log("Sucesso! Foram inseridas/atualizadas " + (result ? result.length : 0) + " habilidades!"); }
}
importSkills();
