const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '../.env.local' });

const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const rawData = `
EF06CI01 | Matéria e energia. Misturas homogêneas e heterogêneas. Separação de materiais. Materiais sintéticos. Transformações químicas | Classificar como homogênea ou heterogênea a mistura de dois ou mais materiais (água e sal, água e óleo, água e areia etc.).
EF06CI02 | Matéria e energia. Misturas homogêneas e heterogêneas. Separação de materiais. Materiais sintéticos. Transformações químicas | Identificar evidências de transformações químicas a partir do resultado de misturas de materiais que originam produtos diferentes dos que foram misturados (mistura de ingredientes para fazer um bolo, mistura de vinagre com bicarbonato de sódio etc.).
EF06CI03 | Matéria e energia. Misturas homogêneas e heterogêneas. Separação de materiais. Materiais sintéticos. Transformações químicas | Selecionar métodos mais adequados para a separação de diferentes sistemas heterogêneos a partir da identificação de processos de separação de materiais (como a produção de sal de cozinha, a destilação de petróleo, entre outros).
EF06CI04 | Matéria e energia. Misturas homogêneas e heterogêneas. Separação de materiais. Materiais sintéticos. Transformações químicas | Associar a produção de medicamentos e outros materiais sintéticos ao desenvolvimento científico e tecnológico, reconhecendo benefícios e avaliando impactos socioambientais.
EF06CI05 | Vida e evolução. Célula como unidade da vida. Interação entre os sistemas locomotor e nervoso. Lentes corretivas | Explicar a organização básica das células e seu papel como unidade estrutural e funcional dos seres vivos.
EF06CI06 | Vida e evolução. Célula como unidade da vida. Interação entre os sistemas locomotor e nervoso. Lentes corretivas | Concluir, com base na análise de ilustrações e/ou modelos (físicos ou digitais), que os organismos são um complexo arranjo de sistemas com diferentes níveis de organização.
EF06CI07 | Vida e evolução. Célula como unidade da vida. Interação entre os sistemas locomotor e nervoso. Lentes corretivas | Justificar o papel do sistema nervoso na coordenação das ações motoras e sensoriais do corpo, com base na análise de suas estruturas básicas e respectivas funções.
EF06CI08 | Vida e evolução. Célula como unidade da vida. Interação entre os sistemas locomotor e nervoso. Lentes corretivas | Explicar a importância da visão (captação e interpretação das imagens) na interação do organismo com o meio e, com base no funcionamento do olho humano, selecionar lentes adequadas para a correção de diferentes defeitos da visão.
EF06CI09 | Vida e evolução. Célula como unidade da vida. Interação entre os sistemas locomotor e nervoso. Lentes corretivas | Deduzir que a estrutura, a sustentação e a movimentação dos animais resultam da interação entre os sistemas muscular, ósseo e nervoso.
EF06CI10 | Vida e evolução. Célula como unidade da vida. Interação entre os sistemas locomotor e nervoso. Lentes corretivas | Explicar como o funcionamento do sistema nervoso pode ser afetado por substâncias psicoativas.
EF06CI11 | Terra e Universo. Forma, estrutura e movimentos da Terra | Identificar as diferentes camadas que estruturam o planeta Terra (da estrutura interna à atmosfera) e suas principais características.
EF06CI12 | Terra e Universo. Forma, estrutura e movimentos da Terra | Identificar diferentes tipos de rocha, relacionando a formação de fósseis a rochas sedimentares em diferentes períodos geológicos.
EF06CI13 | Terra e Universo. Forma, estrutura e movimentos da Terra | Selecionar argumentos e evidências que demonstrem a esfericidade da Terra.
EF06CI14 | Terra e Universo. Forma, estrutura e movimentos da Terra | Inferir que as mudanças na sombra de uma vara (gnômon) ao longo do dia em diferentes períodos do ano são uma evidência dos movimentos relativos entre a Terra e o Sol, que podem ser explicados por meio dos movimentos de rotação e translação da Terra e da inclinação de seu eixo de rotação em relação ao plano de sua órbita em torno do Sol.
EF07CI01 | Matéria e energia. Máquinas simples. Formas de propagação do calor. Equilíbrio termodinâmico e vida na Terra. História dos combustíveis e das máquinas térmicas | Discutir a aplicação, ao longo da história, das máquinas simples e propor soluções e invenções para a realização de tarefas mecânicas cotidianas.
EF07CI02 | Matéria e energia. Máquinas simples. Formas de propagação do calor. Equilíbrio termodinâmico e vida na Terra. História dos combustíveis e das máquinas térmicas | Diferenciar temperatura, calor e sensação térmica nas diferentes situações de equilíbrio termodinâmico cotidianas.
EF07CI03 | Matéria e energia. Máquinas simples. Formas de propagação do calor. Equilíbrio termodinâmico e vida na Terra. História dos combustíveis e das máquinas térmicas | Utilizar o conhecimento das formas de propagação do calor para justificar a utilização de determinados materiais (condutores e isolantes) na vida cotidiana, explicar o princípio de funcionamento de alguns equipamentos (garrafa térmica, coletor solar etc.) e/ou construir soluções tecnológicas a partir desse conhecimento.
EF07CI04 | Matéria e energia. Máquinas simples. Formas de propagação do calor. Equilíbrio termodinâmico e vida na Terra. História dos combustíveis e das máquinas térmicas | Avaliar o papel do equilíbrio termodinâmico para a manutenção da vida na Terra, para o funcionamento de máquinas térmicas e em outras situações cotidianas.
EF07CI05 | Matéria e energia. Máquinas simples. Formas de propagação do calor. Equilíbrio termodinâmico e vida na Terra. História dos combustíveis e das máquinas térmicas | Discutir o uso de diferentes tipos de combustível e máquinas térmicas ao longo do tempo, para avaliar avanços, questões econômicas e problemas socioambientais causados pela produção e uso desses materiais e máquinas.
EF07CI06 | Matéria e energia. Máquinas simples. Formas de propagação do calor. Equilíbrio termodinâmico e vida na Terra. História dos combustíveis e das máquinas térmicas | Discutir e avaliar mudanças econômicas, culturais e sociais, tanto na vida cotidiana quanto no mundo do trabalho, decorrentes do desenvolvimento de novos materiais e tecnologias (como automação e informatização).
EF07CI07 | Vida e evolução. Diversidade de ecossistemas. Fenômenos naturais e impactos ambientais. Programas e indicadores de saúde pública | Caracterizar os principais ecossistemas brasileiros quanto à paisagem, à quantidade de água, ao tipo de solo, à disponibilidade de luz solar, à temperatura etc., correlacionando essas características à flora e fauna específicas.
EF07CI08 | Vida e evolução. Diversidade de ecossistemas. Fenômenos naturais e impactos ambientais. Programas e indicadores de saúde pública | Avaliar como os impactos provocados por catástrofes naturais ou mudanças nos componentes físicos, biológicos ou sociais de um ecossistema afetam suas populações, podendo ameaçar ou provocar a extinção de espécies, alteração de hábitos, migração etc.
EF07CI09 | Vida e evolução. Diversidade de ecossistemas. Fenômenos naturais e impactos ambientais. Programas e indicadores de saúde pública | Interpretar as condições de saúde da comunidade, cidade ou estado, com base na análise e comparação de indicadores de saúde (como taxa de mortalidade infantil, cobertura de saneamento básico e incidência de doenças de veiculação hídrica, atmosférica entre outras) e dos resultados de políticas públicas destinadas à saúde.
EF07CI10 | Vida e evolução. Diversidade de ecossistemas. Fenômenos naturais e impactos ambientais. Programas e indicadores de saúde pública | Argumentar sobre a importância da vacinação para a saúde pública, com base em informações sobre a maneira como a vacina atua no organismo e o papel histórico da vacinação para a manutenção da saúde individual e coletiva e para a erradicação de doenças.
EF07CI11 | Vida e evolução. Diversidade de ecossistemas. Fenômenos naturais e impactos ambientais. Programas e indicadores de saúde pública | Analisar historicamente o uso da tecnologia, incluindo a digital, nas diferentes dimensões da vida humana, considerando indicadores ambientais e de qualidade de vida.
EF07CI12 | Terra e Universo. Composição do ar. Efeito estufa. Camada de ozônio. Fenômenos naturais (vulcões, terremotos e tsunamis). Placas tectônicas e deriva continental | Demonstrar que o ar é uma mistura de gases, identificando sua composição, e discutir fenômenos naturais ou antrópicos que podem alterar essa composição.
EF07CI13 | Terra e Universo. Composição do ar. Efeito estufa. Camada de ozônio. Fenômenos naturais (vulcões, terremotos e tsunamis). Placas tectônicas e deriva continental | Descrever o mecanismo natural do efeito estufa, seu papel fundamental para o desenvolvimento da vida na Terra, discutir as ações humanas responsáveis pelo seu aumento artificial (queima dos combustíveis fósseis, desmatamento, queimadas etc.) e selecionar e implementar propostas para a reversão ou controle desse quadro.
EF07CI14 | Terra e Universo. Composição do ar. Efeito estufa. Camada de ozônio. Fenômenos naturais (vulcões, terremotos e tsunamis). Placas tectônicas e deriva continental | Justificar a importância da camada de ozônio para a vida na Terra, identificando os fatores que aumentam ou diminuem sua presença na atmosfera, e discutir propostas individuais e coletivas para sua preservação.
EF07CI15 | Terra e Universo. Composição do ar. Efeito estufa. Camada de ozônio. Fenômenos naturais (vulcões, terremotos e tsunamis). Placas tectônicas e deriva continental | Interpretar fenômenos naturais (como vulcões, terremotos e tsunamis) e justificar a rara ocorrência desses fenômenos no Brasil, com base no modelo das placas tectônicas.
EF07CI16 | Terra e Universo. Composição do ar. Efeito estufa. Camada de ozônio. Fenômenos naturais (vulcões, terremotos e tsunamis). Placas tectônicas e deriva continental | Justificar o formato das costas brasileira e africana com base na teoria da deriva dos continentes.
EF08CI01 | Matéria e energia. Fontes e tipos de energia. Transformação de energia. Cálculo de consumo de energia elétrica. Circuitos elétricos. Uso consciente de energia elétrica | Identificar e classificar diferentes fontes (renováveis e não renováveis) e tipos de energia utilizados em residências, comunidades ou cidades.
EF08CI02 | Matéria e energia. Fontes e tipos de energia. Transformação de energia. Cálculo de consumo de energia elétrica. Circuitos elétricos. Uso consciente de energia elétrica | Construir circuitos elétricos com pilha/bateria, fios e lâmpada ou outros dispositivos e compará-los a circuitos elétricos residenciais.
EF08CI03 | Matéria e energia. Fontes e tipos de energia. Transformação de energia. Cálculo de consumo de energia elétrica. Circuitos elétricos. Uso consciente de energia elétrica | Classificar equipamentos elétricos residenciais (chuveiro, ferro, lâmpadas, TV, rádio, geladeira etc.) de acordo com o tipo de transformação de energia (da energia elétrica para a térmica, luminosa, sonora e mecânica, por exemplo).
EF08CI04 | Matéria e energia. Fontes e tipos de energia. Transformação de energia. Cálculo de consumo de energia elétrica. Circuitos elétricos. Uso consciente de energia elétrica | Calcular o consumo de eletrodomésticos a partir dos dados de potência (descritos no próprio equipamento) e tempo médio de uso para avaliar o impacto de cada equipamento no consumo doméstico mensal.
EF08CI05 | Matéria e energia. Fontes e tipos de energia. Transformação de energia. Cálculo de consumo de energia elétrica. Circuitos elétricos. Uso consciente de energia elétrica | Propor ações coletivas para otimizar o uso de energia elétrica em sua escola e/ou comunidade, com base na seleção de equipamentos segundo critérios de sustentabilidade (consumo de energia e eficiência energética) e hábitos de consumo responsável.
EF08CI06 | Matéria e energia. Fontes e tipos de energia. Transformação de energia. Cálculo de consumo de energia elétrica. Circuitos elétricos. Uso consciente de energia elétrica | Discutir e avaliar usinas de geração de energia elétrica (termelétricas, hidrelétricas, eólicas etc.), suas semelhanças e diferenças, seus impactos socioambientais, e como essa energia chega e é usada em sua cidade, comunidade, casa ou escola.
EF08CI07 | Vida e evolução. Mecanismos reprodutivos. Sexualidade | Comparar diferentes processos reprodutivos em plantas e animais em relação aos mecanismos adaptativos e evolutivos.
EF08CI08 | Vida e evolução. Mecanismos reprodutivos. Sexualidade | Analisar e explicar as transformações que ocorrem na puberdade considerando a atuação dos hormônios sexuais e do sistema nervoso.
EF08CI09 | Vida e evolução. Mecanismos reprodutivos. Sexualidade | Comparar o modo de ação e a eficácia dos diversos métodos contraceptivos e justificar a necessidade de compartilhar a responsabilidade na escolha e na utilização do método mais adequado à prevenção da gravidez precoce e indesejada e de Doenças Sexualmente Transmissíveis (DST).
EF08CI10 | Vida e evolução. Mecanismos reprodutivos. Sexualidade | Identificar os principais sintomas, modos de transmissão e tratamento de algumas DST (com ênfase na AIDS), e discutir estratégias e métodos de prevenção.
EF08CI11 | Vida e evolução. Mecanismos reprodutivos. Sexualidade | Selecionar argumentos que evidenciem as múltiplas dimensões da sexualidade humana (biológica, sociocultural, afetiva e ética).
EF08CI12 | Terra e Universo. Sistema Sol, Terra e Lua. Clima | Justificar, por meio da construção de modelos e da observação da Lua no céu, a ocorrência das fases da Lua e dos eclipses, com base nas posições relativas entre Sol, Terra e Lua.
EF08CI13 | Terra e Universo. Sistema Sol, Terra e Lua. Clima | Representar os movimentos de rotação e translação da Terra e analisar o papel da inclinação do eixo de rotação da Terra em relação à sua órbita na ocorrência das estações do ano, com a utilização de modelos tridimensionais.
EF08CI14 | Terra e Universo. Sistema Sol, Terra e Lua. Clima | Relacionar climas regionais aos padrões de circulação atmosférica e oceânica e ao aquecimento desigual causado pela forma e pelos movimentos da Terra.
EF08CI15 | Terra e Universo. Sistema Sol, Terra e Lua. Clima | Identificar as principais variáveis envolvidas na previsão do tempo e simular situações nas quais elas possam ser medidas.
EF08CI16 | Terra e Universo. Sistema Sol, Terra e Lua. Clima | Discutir iniciativas que contribuam para restabelecer o equilíbrio ambiental a partir da identificação de alterações climáticas regionais e globais provocadas pela intervenção humana.
EF09CI01 | Matéria e energia. Aspectos quantitativos das transformações químicas. Estrutura da matéria. Radiações e suas aplicações na saúde | Investigar as mudanças de estado físico da matéria e explicar essas transformações com base no modelo de constituição submicroscópica.
EF09CI02 | Matéria e energia. Aspectos quantitativos das transformações químicas. Estrutura da matéria. Radiações e suas aplicações na saúde | Comparar quantidades de reagentes e produtos envolvidos em transformações químicas, estabelecendo a proporção entre as suas massas.
EF09CI03 | Matéria e energia. Aspectos quantitativos das transformações químicas. Estrutura da matéria. Radiações e suas aplicações na saúde | Identificar modelos que descrevem a estrutura da matéria (constituição do átomo e composição de moléculas simples) e reconhecer sua evolução histórica.
EF09CI04 | Matéria e energia. Aspectos quantitativos das transformações químicas. Estrutura da matéria. Radiações e suas aplicações na saúde | Planejar e executar experimentos que evidenciem que todas as cores de luz podem ser formadas pela composição das três cores primárias da luz e que a cor de um objeto está relacionada também à cor da luz que o ilumina.
EF09CI05 | Matéria e energia. Aspectos quantitativos das transformações químicas. Estrutura da matéria. Radiações e suas aplicações na saúde | Investigar os principais mecanismos envolvidos na transmissão e recepção de imagem e som que revolucionaram os sistemas de comunicação humana.
EF09CI06 | Matéria e energia. Aspectos quantitativos das transformações químicas. Estrutura da matéria. Radiações e suas aplicações na saúde | Classificar as radiações eletromagnéticas por suas frequências, fontes e aplicações, discutindo e avaliando as implicações de seu uso em controle remoto, telefone celular, raio X, forno de micro-ondas, fotocélulas etc.
EF09CI07 | Matéria e energia. Aspectos quantitativos das transformações químicas. Estrutura da matéria. Radiações e suas aplicações na saúde | Discutir o papel do avanço tecnológico na aplicação das radiações na medicina diagnóstica (raio X, ultrassom, ressonância nuclear magnética) e no tratamento de doenças (radioterapia, cirurgia ótica a laser, infravermelho, ultravioleta etc.).
EF09CI08 | Vida e evolução. Hereditariedade. Ideias evolucionistas. Preservação da biodiversidade | Associar os gametas à transmissão das características hereditárias, estabelecendo relações entre ancestrais e descendentes.
EF09CI09 | Vida e evolução. Hereditariedade. Ideias evolucionistas. Preservação da biodiversidade | Discutir as ideias de Mendel sobre hereditariedade (fatores hereditários, segregação, gametas, fecundação), considerando-as para resolver problemas envolvendo a transmissão de características hereditárias em diferentes organismos.
EF09CI10 | Vida e evolução. Hereditariedade. Ideias evolucionistas. Preservação da biodiversidade | Comparar as ideias evolucionistas de Lamarck e Darwin apresentadas em textos científicos e históricos, identificando semelhanças e diferenças entre essas ideias e sua importância para explicar a diversidade biológica.
EF09CI11 | Vida e evolução. Hereditariedade. Ideias evolucionistas. Preservação da biodiversidade | Discutir a evolução e a diversidade das espécies com base na atuação da seleção natural sobre as variantes de uma mesma espécie, resultantes de processo reprodutivo.
EF09CI12 | Vida e evolução. Hereditariedade. Ideias evolucionistas. Preservação da biodiversidade | Justificar a importância das unidades de conservação para a preservação da biodiversidade e do patrimônio nacional, considerando os diferentes tipos de unidades (parques, reservas e florestas nacionais), as populações humanas e as atividades a eles relacionadas.
EF09CI13 | Vida e evolução. Hereditariedade. Ideias evolucionistas. Preservação da biodiversidade | Propor iniciativas individuais e coletivas para a solução de problemas ambientais da cidade ou da comunidade, com base na análise de ações de consumo consciente e de sustentabilidade bem-sucedidas.
EF09CI14 | Terra e Universo. Composição, estrutura e localização do Sistema Solar no Universo. Astronomia e cultura. Vida humana fora da Terra. Ordem de grandeza astronômica. Evolução estelar | Descrever a composição e a estrutura do Sistema Solar (Sol, planetas rochosos, planetas gigantes gasosos e corpos menores), assim como a localização do Sistema Solar na nossa Galáxia (a Via Láctea) e dela no Universo (apenas uma galáxia dentre bilhões).
EF09CI15 | Terra e Universo. Composição, estrutura e localização do Sistema Solar no Universo. Astronomia e cultura. Vida humana fora da Terra. Ordem de grandeza astronômica. Evolução estelar | Relacionar diferentes leituras do céu e explicações sobre a origem da Terra, do Sol ou do Sistema Solar às necessidades de distintas culturas (agricultura, caça, mito, orientação espacial e temporal etc.).
EF09CI16 | Terra e Universo. Composição, estrutura e localização do Sistema Solar no Universo. Astronomia e cultura. Vida humana fora da Terra. Ordem de grandeza astronômica. Evolução estelar | Selecionar argumentos sobre a viabilidade da sobrevivência humana fora da Terra, com base nas condições necessárias à vida, nas características dos planetas e nas distâncias e nos tempos envolvidos em viagens interplanetárias e interestelares.
EF09CI17 | Terra e Universo. Composição, estrutura e localização do Sistema Solar no Universo. Astronomia e cultura. Vida humana fora da Terra. Ordem de grandeza astronômica. Evolução estelar | Analisar o ciclo evolutivo do Sol (nascimento, vida e morte) baseado no conhecimento das etapas de evolução de estrelas de diferentes dimensões e os efeitos desse processo no nosso planeta.
`;

async function importSkills() {
    const lines = rawData.trim().split('\n');
    const skillsToInsert = [];
    for (let line of lines) {
        if (!line.trim()) continue;
        const parts = line.split('|').map(p => p.trim());
        if (parts.length >= 3) {
            const code = parts[0];
            const knowledgeObject = parts[1];
            const description = parts.slice(2).join(' | ');
            const yearMatch = code.match(/EF(\d{2})/);
            const year_range = yearMatch ? "EF" + yearMatch[1] : "EF00";
            const fullDescription = "[Objeto de Conhecimento: " + knowledgeObject + "] " + description;

            skillsToInsert.push({ code, description: fullDescription, subject: "CIÊNCIAS", year_range });
        }
    }
    if (skillsToInsert.length === 0) { console.log("Nenhuma habilidade encontrada."); return; }
    console.log("Preparando para inserir " + skillsToInsert.length + " habilidades...");
    const { data: result, error } = await supabase.from('bncc_skills').upsert(skillsToInsert, { onConflict: 'code' }).select();
    if (error) { console.error("Erro na inserção:", error); }
    else { console.log("Sucesso! Foram inseridas/atualizadas " + (result ? result.length : 0) + " habilidades!"); }
}
importSkills();
